### ISSUE TITLE
How can I get the proj.npy file in phase retrival code?

### ISSUE THREAD

**Issue by bemoregt** [arslansadiq/Image-Processing-In-Physics#1]
Hi, @arslansadiq 

How can I get the proj.npy file in phase retrival code?

Thanks.
Best,
@bemoregt.

**Comment by arslansadiq** [comment]
Hi,
I hope that you are fine.
I have uploaded the file.

Regards

**Comment by bemoregt** [comment]
Thanks a lot ~!!

Best’
@bemoregt. 

나의 iPhone에서 보냄

2020. 4. 7. 오후 9:02, Muhammad Arslan Ansari <notifications@github.com> 작성:
